function replacer(str) {
    var pairs = {
          "ACC":"<div class='tooltip'>ACC<span class='tooltiptext'>Accident and Compensation Cases</span></div>",
          "ACC(SC)":"<div class='tooltip'>ACC(SC)<span class='tooltiptext'>Accident and Compensation Cases (SC)</span></div>",
          "ACJ":"<div class='tooltip'>ACJ<span class='tooltiptext'>Accidents Claims Journal</span></div>",
          "AIHC":"<div class='tooltip'>AIHC<span class='tooltiptext'>All India High Court Cases</span></div>",
          "FAJ":"<div class='tooltip'>FAJ<span class='tooltiptext'>All India Prevention of Food Adulteration Journal</span></div>",
          "AIR":"<div class='tooltip'>AIR<span class='tooltiptext'>All India Reporter</span></div>",
          "AIR(Mys)":"<div class='tooltip'>AIR(Mys)<span class='tooltiptext'>All India Reporter (Mys)</span></div>",
          "ALLMR":"<div class='tooltip'>ALLMR<span class='tooltiptext'>ALL MAHARASHTRA LAW REPORTER</span></div>",
          "ALLMR (SC)":"<div class='tooltip'>ALLMR (SC)<span class='tooltiptext'>ALL MAHARASHTRA LAW REPORTER SC</span></div>",
          "ALLMR(Cri)":"<div class='tooltip'>ALLMR(Cri)<span class='tooltiptext'>ALL MAHARSHTRA LAW REPORTER (Cri)</span></div>",
          "ARC":"<div class='tooltip'>ARC<span class='tooltiptext'>Allahabad Rent Cases</span></div>",
          "AWC":"<div class='tooltip'>AWC<span class='tooltiptext'>Allahabad Weekly Cases</span></div>",
          "AWCSC":"<div class='tooltip'>AWCSC<span class='tooltiptext'>Allahabad Weekly Cases (Supp - SC)</span></div>",
          "AWCUHC":"<div class='tooltip'>AWCUHC<span class='tooltiptext'>Allahabad Weekly Cases UHC</span></div>",
          "ALT":"<div class='tooltip'>ALT<span class='tooltiptext'>Andhra Law Times</span></div>",
          "ALT(Cri)":"<div class='tooltip'>ALT(Cri)<span class='tooltiptext'>Andhra Law Times (Criminal)</span></div>",
          "ALT(SC)":"<div class='tooltip'>ALT(SC)<span class='tooltiptext'>Andhra Law Times(SC)</span></div>",
          "ALD(Cri)":"<div class='tooltip'>ALD(Cri)<span class='tooltiptext'>Andhra Legal Decision (Criminal)</span></div>",
          "ALD":"<div class='tooltip'>ALD<span class='tooltiptext'>Andhra Legal Decisions</span></div>",
          "ALD-SC":"<div class='tooltip'>ALD-SC<span class='tooltiptext'>Andhra Legal Decisions (SC)</span></div>",
          "APLJ":"<div class='tooltip'>APLJ<span class='tooltiptext'>Andhra Pradesh Law Journal</span></div>",
          "AnWR":"<div class='tooltip'>AnWR<span class='tooltiptext'>Andhra Weekly Reporter</span></div>",
          "AD":"<div class='tooltip'>AD<span class='tooltiptext'>Apex Decision</span></div>",
          "ARBLR":"<div class='tooltip'>ARBLR<span class='tooltiptext'>Arbitration Law Reporter</span></div>",
          "BC":"<div class='tooltip'>BC<span class='tooltiptext'>Banking Cases</span></div>",
          "BC-SC":"<div class='tooltip'>BC-SC<span class='tooltiptext'>Banking Cases with court</span></div>",
          "BLJR":"<div class='tooltip'>BLJR<span class='tooltiptext'>Bihar Law Journal Reports</span></div>",
          "BomCR":"<div class='tooltip'>BomCR<span class='tooltiptext'>Bombay Cases Reporter</span></div>",
          "BomCR(Cri)":"<div class='tooltip'>BomCR(Cri)<span class='tooltiptext'>Bombay Cases Reporter (Criminal)</span></div>",
          "BomCRSupp":"<div class='tooltip'>BomCRSupp<span class='tooltiptext'>Bombay Cases Reporter(Supp)</span></div>",
          "BOMLR":"<div class='tooltip'>BOMLR<span class='tooltiptext'>Bombay Law Reporter</span></div>",
          "BusLR":"<div class='tooltip'>BusLR<span class='tooltiptext'>Business Law Reports</span></div>",
          "CHN":"<div class='tooltip'>CHN<span class='tooltiptext'>Calcutta High Court Notes</span></div>",
          "CHN(SC)":"<div class='tooltip'>CHN(SC)<span class='tooltiptext'>Calcutta High Court Notes (SC)</span></div>",
          "CALLT":"<div class='tooltip'>CALLT<span class='tooltiptext'>Calcutta Law Times</span></div>",
          "CWN":"<div class='tooltip'>CWN<span class='tooltiptext'>Calcutta Weekly Notes</span></div>",
          "CivilCC":"<div class='tooltip'>CivilCC<span class='tooltiptext'>Civil Court Cases</span></div>",
          "CivilCCSup":"<div class='tooltip'>CivilCCSup<span class='tooltiptext'>Civil Court Cases (Supp)</span></div>",
          "CompCas":"<div class='tooltip'>CompCas<span class='tooltiptext'>Company Cases</span></div>",
          "CompLJ":"<div class='tooltip'>CompLJ<span class='tooltiptext'>Company Law Journal</span></div>",
          "CompAT":"<div class='tooltip'>CompAT<span class='tooltiptext'>Competition Law Reports</span></div>",
          "CPJ":"<div class='tooltip'>CPJ<span class='tooltiptext'>Consumer Protection Judgments</span></div>",
          "CTLJ":"<div class='tooltip'>CTLJ<span class='tooltiptext'>Contracts and Tenders Law Journal</span></div>",
          "CLA":"<div class='tooltip'>CLA<span class='tooltiptext'>Corporate Law Adviser</span></div>",
          "CLA-BL-Sup":"<div class='tooltip'>CLA-BL-Sup<span class='tooltiptext'>Corporate Law Advisor – Business Law Supplement</span></div>",
          "Crime":"<div class='tooltip'>Crime<span class='tooltiptext'>Crimes</span></div>",
          "Crimes":"<div class='tooltip'>Crimes<span class='tooltiptext'>Crimes (SC)</span></div>",
          "CriLJ":"<div class='tooltip'>CriLJ<span class='tooltiptext'>Criminal Law Journal</span></div>",
          "CCR":"<div class='tooltip'>CCR<span class='tooltiptext'>Current Criminal Reports</span></div>",
          "CCR(SC)":"<div class='tooltip'>CCR(SC)<span class='tooltiptext'>Current Criminal Reports (SC)</span></div>",
          "CTC":"<div class='tooltip'>CTC<span class='tooltiptext'>Current Tamil Nadu Cases</span></div>",
          "CTR":"<div class='tooltip'>CTR<span class='tooltiptext'>Current Tax Reporter</span></div>",
          "CLT":"<div class='tooltip'>CLT<span class='tooltiptext'>Cuttack Law Times</span></div>",
          "CLT(SC)":"<div class='tooltip'>CLT(SC)<span class='tooltiptext'>Cuttack Law Times (SC)</span></div>",
          "CWN":"<div class='tooltip'>CWN<span class='tooltiptext'>Calcutta Weekly Notes</span></div>",
          "DLT":"<div class='tooltip'>DLT<span class='tooltiptext'>Delhi Law Times</span></div>",
          "DLT(SC)":"<div class='tooltip'>DLT(SC)<span class='tooltiptext'>Delhi Law Times (SC)</span></div>",
          "DRJ":"<div class='tooltip'>DRJ<span class='tooltiptext'>Delhi Reported Journal</span></div>",
          "DRJSupp":"<div class='tooltip'>DRJSupp<span class='tooltiptext'>Delhi Reported Journal (Suppl)</span></div>",
          "DRJSupp NV":"<div class='tooltip'>DRJSupp NV<span class='tooltiptext'>Delhi Reported Journal (Suppl)without Volume</span></div>",
          "DMC":"<div class='tooltip'>DMC<span class='tooltiptext'>Divorce and Matrimonial Cases</span></div>",
          "DMC(SC)":"<div class='tooltip'>DMC(SC)<span class='tooltiptext'>Divorce and Matrimonial Cases (SC)</span></div>",
          "ESC":"<div class='tooltip'>ESC<span class='tooltiptext'>Education and Service Cases</span></div>",
          "ELR":"<div class='tooltip'>ELR<span class='tooltiptext'>Energy Law Reports</span></div>",
          "ECC":"<div class='tooltip'>ECC<span class='tooltiptext'>Excise & Customs Cases</span></div>",
          "ECR":"<div class='tooltip'>ECR<span class='tooltiptext'>Excise and Custom Reprots (Without Volume)</span></div>",
          "ELT":"<div class='tooltip'>ELT<span class='tooltiptext'>Excise Law Times</span></div>",
          "FLR":"<div class='tooltip'>FLR<span class='tooltiptext'>Factory Law Reporter</span></div>",
          "GLD":"<div class='tooltip'>GLD<span class='tooltiptext'>Gauhati Law Decisions</span></div>",
          "GLDSupp":"<div class='tooltip'>GLDSupp<span class='tooltiptext'>Gauhati Law Decisions Supp</span></div>",
          "GauLR":"<div class='tooltip'>GauLR<span class='tooltiptext'>Gauhati Law Reports</span></div>",
          "GLT":"<div class='tooltip'>GLT<span class='tooltiptext'>Gauhati Law Times</span></div>",
          "GLT(SC)":"<div class='tooltip'>GLT(SC)<span class='tooltiptext'>Gauhati Law Times (SC)</span></div>",
          "GLH":"<div class='tooltip'>GLH<span class='tooltiptext'>Gujarat Law Herald</span></div>",
          "GLR":"<div class='tooltip'>GLR<span class='tooltiptext'>Gujarat Law Reporter</span></div>",
          "GLR (FB)":"<div class='tooltip'>GLR (FB)<span class='tooltiptext'>Gujarat Law Reporter (FB)</span></div>",
          "GLR (SC)":"<div class='tooltip'>GLR (SC)<span class='tooltiptext'>Gujarat Law Reporter (SC)</span></div>",
          "ITR":"<div class='tooltip'>ITR<span class='tooltiptext'>Income Tax Reporter</span></div>",
          "ITD":"<div class='tooltip'>ITD<span class='tooltiptext'>Income-tax Tribunal Decisions</span></div>",
          "Ind.Cas.":"<div class='tooltip'>Ind.Cas.<span class='tooltiptext'>Indian Cases</span></div>",
          "ILR":"<div class='tooltip'>ILR<span class='tooltiptext'>Indian Law Reports</span></div>",
          "ILR (Bom)":"<div class='tooltip'>ILR (Bom)<span class='tooltiptext'>Indian Law Reports (Bombay)</span></div>",
          "ILR (PC)":"<div class='tooltip'>ILR (PC)<span class='tooltiptext'>Indian Law Reports (P C)</span></div>",
          "ILR Pre":"<div class='tooltip'>ILR Pre<span class='tooltiptext'>Indian Law Reports (Pre)</span></div>",
          "ITDSB":"<div class='tooltip'>ITDSB<span class='tooltiptext'>ITD Special Bench</span></div>",
          "JCR":"<div class='tooltip'>JCR<span class='tooltiptext'>Jharkhand Cases Reporter</span></div>",
          "JKJ":"<div class='tooltip'>JKJ<span class='tooltiptext'>JK Judgments</span></div>",
          "JKJ [SC]":"<div class='tooltip'>JKJ [SC]<span class='tooltiptext'>JK Judgments [SC]</span></div>",
          "JCC":"<div class='tooltip'>JCC<span class='tooltiptext'>Journal Of Criminal Cases</span></div>",
          "JCC(SC)":"<div class='tooltip'>JCC(SC)<span class='tooltiptext'>Journal Of Criminal Cases (SC)</span></div>",
          "JT":"<div class='tooltip'>JT<span class='tooltiptext'>Judgment Today</span></div>",
          "JT (Suppl)":"<div class='tooltip'>JT (Suppl)<span class='tooltiptext'>Judgment Today Supplement</span></div>",
          "KCCR":"<div class='tooltip'>KCCR<span class='tooltiptext'>Karnataka Civil and Criminal Reporter</span></div>",
          "KarLJ":"<div class='tooltip'>KarLJ<span class='tooltiptext'>Karnataka Law Journal</span></div>",
          "KLJ":"<div class='tooltip'>KLJ<span class='tooltiptext'>Kerala Law Journal</span></div>",
          "KLT":"<div class='tooltip'>KLT<span class='tooltiptext'>Kerala Law Times</span></div>",
          "KLT (SC)":"<div class='tooltip'>KLT (SC)<span class='tooltiptext'>Kerala Law Times (SC)</span></div>",
          "LabIC":"<div class='tooltip'>LabIC<span class='tooltiptext'>Labour and Industrial cases</span></div>",
          "LLJ":"<div class='tooltip'>LLJ<span class='tooltiptext'>Labour Law Journal</span></div>",
          "LS":"<div class='tooltip'>LS<span class='tooltiptext'>Law Summary</span></div>",
          "MPLJ":"<div class='tooltip'>MPLJ<span class='tooltiptext'>M.P. Law Journal</span></div>",
          "MPLJ(SC)":"<div class='tooltip'>MPLJ(SC)<span class='tooltiptext'>M.P. Law Journal(SC)</span></div>",
          "MLJ":"<div class='tooltip'>MLJ<span class='tooltiptext'>Madras Law Journal</span></div>",
          "MLJ(SC)":"<div class='tooltip'>MLJ(SC)<span class='tooltiptext'>Madras Law Journal (SC)</span></div>",
          "MhLj":"<div class='tooltip'>MhLj<span class='tooltiptext'>Maharashtra Law Journal</span></div>",
          "MhLJ(SC)":"<div class='tooltip'>MhLJ(SC)<span class='tooltiptext'>Maharastra Law Journal SC</span></div>",
          "MIPR":"<div class='tooltip'>MIPR<span class='tooltiptext'>MIPR</span></div>",
          "M.I.A.":"<div class='tooltip'>M.I.A.<span class='tooltiptext'>Moores Indian Appeals</span></div>",
          "MPHT":"<div class='tooltip'>MPHT<span class='tooltiptext'>MP High Court Today</span></div>",
          "MPHT(CG)":"<div class='tooltip'>MPHT(CG)<span class='tooltiptext'>MP High Court Today with court</span></div>",
          "MysLJ":"<div class='tooltip'>MysLJ<span class='tooltiptext'>Mysore Law Journal</span></div>",
          "MysLJ(SC)":"<div class='tooltip'>MysLJ(SC)<span class='tooltiptext'>Mysore Law Journal (SC)</span></div>",
          "OLR":"<div class='tooltip'>OLR<span class='tooltiptext'>Orissa Law Reviews</span></div>",
          "OLR (SC)":"<div class='tooltip'>OLR (SC)<span class='tooltiptext'>Orissa Law Reviews (SC)</span></div>",
          "PTC":"<div class='tooltip'>PTC<span class='tooltiptext'>Patent & Trade Marks Cases</span></div>",
          "PLR":"<div class='tooltip'>PLR<span class='tooltiptext'>Punjab Law Reporter</span></div>",
          "RLR":"<div class='tooltip'>RLR<span class='tooltiptext'>Rajasthan Law Reporter</span></div>",
          "RLW":"<div class='tooltip'>RLW<span class='tooltiptext'>Rajasthan Law Weekly</span></div>",
          "RAJ":"<div class='tooltip'>RAJ<span class='tooltiptext'>Rajdhani Law Reporter</span></div>",
          "RArJ":"<div class='tooltip'>RArJ<span class='tooltiptext'>Recent Arbitration Judgments</span></div>",
          "RAJ(SC)":"<div class='tooltip'>RAJ(SC)<span class='tooltiptext'>Recent Arbitration Judgments (SC)</span></div>",
          "RLT":"<div class='tooltip'>RLT<span class='tooltiptext'>Revenue Law Times</span></div>",
          "STC":"<div class='tooltip'>STC<span class='tooltiptext'>Sales Tax Cases</span></div>",
          "SCR no vol":"<div class='tooltip'>SCR no vol<span class='tooltiptext'>SCR Supp without Volume</span></div>",
          "SCL":"<div class='tooltip'>SCL<span class='tooltiptext'>Sebi and Corporate laws</span></div>",
          "SOT":"<div class='tooltip'>SOT<span class='tooltiptext'>Selected Orders of ITAT</span></div>",
          "SCT":"<div class='tooltip'>SCT<span class='tooltiptext'>Service Cases Today</span></div>",
          "STJ":"<div class='tooltip'>STJ<span class='tooltiptext'>Service Tax Journal</span></div>",
          "STR":"<div class='tooltip'>STR<span class='tooltiptext'>Service Tax Review</span></div>",
          "SLJ":"<div class='tooltip'>SLJ<span class='tooltiptext'>Services Law Journal</span></div>",
          "SLR":"<div class='tooltip'>SLR<span class='tooltiptext'>Services Law Reporter</span></div>",
          "SLR(SC)":"<div class='tooltip'>SLR(SC)<span class='tooltiptext'>Services Law Reporter (SC)</span></div>",
          "ShimLC":"<div class='tooltip'>ShimLC<span class='tooltiptext'>Shimla Law Cases</span></div>",
          "SCALE":"<div class='tooltip'>SCALE<span class='tooltiptext'>Supreme Court Almanac</span></div>",
          "SCC":"<div class='tooltip'>SCC<span class='tooltiptext'>Supreme Court Cases</span></div>",
          "SCC (Supp)":"<div class='tooltip'>SCC (Supp)<span class='tooltiptext'>Supreme Court Cases (Supp)</span></div>",
          "SCR":"<div class='tooltip'>SCR<span class='tooltiptext'>Supreme Court Reporter</span></div>",
          "TTJ":"<div class='tooltip'>TTJ<span class='tooltiptext'>Tax Tribunal Judgments</span></div>",
          "TAXLR":"<div class='tooltip'>TAXLR<span class='tooltiptext'>Taxation Law Reporter</span></div>",
          "TAXMAN":"<div class='tooltip'>TAXMAN<span class='tooltiptext'>TAXMAN</span></div>",
          "STT":"<div class='tooltip'>STT<span class='tooltiptext'>Taxman's Service Tax Today</span></div>",
          "Ind.Ap.":"<div class='tooltip'>Ind.Ap.<span class='tooltiptext'>The Law Report - Indian Appeals</span></div>",
          "Ind.Ap.sv":"<div class='tooltip'>Ind.Ap.sv<span class='tooltiptext'>The Law Report - Indian Appeals(Supp. Vol.)</span></div>",
          "UJ":"<div class='tooltip'>UJ<span class='tooltiptext'>The Unreported Judgments</span></div>",
          "UPLBEC":"<div class='tooltip'>UPLBEC<span class='tooltiptext'>U.P. Local Bodies & Educational Cases</span></div>",
          "VST":"<div class='tooltip'>VST<span class='tooltiptext'>VAT AND SERVICE TAX CASES</span></div>",
          "VR":"<div class='tooltip'>VR<span class='tooltiptext'>Vat Reporter</span></div>",
          "WLN":"<div class='tooltip'>WLN<span class='tooltiptext'>Weekly Law Notes</span></div>",
          "WLNRev":"<div class='tooltip'>WLNRev<span class='tooltiptext'>Weekly Law Notes Revenue</span></div>",
          "WLNUC":"<div class='tooltip'>WLNUC<span class='tooltiptext'>Weekly Law Notes UC</span></div>",
          "WLNWV":"<div class='tooltip'>WLNWV<span class='tooltiptext'>Weekly Law Notes Without Volume</span></div>",
          "WLC":"<div class='tooltip'>WLC<span class='tooltiptext'>Western Law Cases</span></div>",
          "WLC(Raj)UC":"<div class='tooltip'>WLC(Raj)UC<span class='tooltiptext'>Western Law Cases (Raj) UC</span></div>",
          "W/o":"<div class='tooltip'>W/o<span class='tooltiptext'>wife of</span></div>",
          "W.H.O":"<div class='tooltip'>W.H.O<span class='tooltiptext'>World Health Organization</span></div>",
          "WIA":"<div class='tooltip'>WIA<span class='tooltiptext'>The Women�s Indian Association</span></div>",
          "VAW":"<div class='tooltip'>VAW<span class='tooltiptext'>Violence against Women</span></div>",
          "USA":"<div class='tooltip'>USA<span class='tooltiptext'>United States of America</span></div>",
          "UOI":"<div class='tooltip'>UOI<span class='tooltiptext'>Union Of India</span></div>",
          "UNTF":"<div class='tooltip'>UNTF<span class='tooltiptext'>United Nations Trust Fund to End Violence against Women</span></div>",
          "PIL":"<div class='tooltip'>PIL<span class='tooltiptext'>Public Interest Litigation</span></div>",
          "POs":"<div class='tooltip'>POs<span class='tooltiptext'>Protection Officers</span></div>",
          "PWDVA":"<div class='tooltip'>PWDVA<span class='tooltiptext'>Protection of Women from Domestic Violence Act, 2005 Domestic Violence Act</span></div>",
          "PWDVR":"<div class='tooltip'>PWDVR<span class='tooltiptext'>Protection of Women from Domestic Violence Rules, 2006</span></div>",
          "RTI":"<div class='tooltip'>RTI<span class='tooltiptext'>Right to Information</span></div>",
          "S/o":"<div class='tooltip'>S/o<span class='tooltiptext'>Son of</span></div>",
          "SC":"<div class='tooltip'>SC<span class='tooltiptext'>Supreme Court</span></div>",
          "SEWA":"<div class='tooltip'>SEWA<span class='tooltiptext'>Self Employed Women's Association</span></div>",
          "SH":"<div class='tooltip'>SH<span class='tooltiptext'>Shared Household</span></div>",
          "SLP":"<div class='tooltip'>SLP<span class='tooltiptext'>Special Leave Petition</span></div>",
          "SPs":"<div class='tooltip'>SPs<span class='tooltiptext'>Service Providers</span></div>",
          "u/a":"<div class='tooltip'>u/a<span class='tooltiptext'>Under Article</span></div>",
          "UCC":"<div class='tooltip'>UCC<span class='tooltiptext'>Uniform Civil Code</span></div>",
          "u/s":"<div class='tooltip'>u/s<span class='tooltiptext'>Under Section</span></div>",
          "UNDP":"<div class='tooltip'>UNDP<span class='tooltiptext'>United Nations Development Programme</span></div>",
          "UNESCO":"<div class='tooltip'>UNESCO<span class='tooltiptext'>United Nations Educational Scientific and Cultural Organisation</span></div>",
          "UNGA":"<div class='tooltip'>UNGA<span class='tooltiptext'>United Nation General Assembly</span></div>",
          "UNIFEM":"<div class='tooltip'>UNIFEM<span class='tooltiptext'>United Nations Development Fund for Women</span></div>",
          "UNO":"<div class='tooltip'>UNO<span class='tooltiptext'>United Nations Organization</span></div>",
          "NALSA":"<div class='tooltip'>NALSA<span class='tooltiptext'>National Legal Services Authority</span></div>",
          "NCC":"<div class='tooltip'>NCC<span class='tooltiptext'>National Crime Record</span></div>",
          "NCT":"<div class='tooltip'>NCT<span class='tooltiptext'>National Capital Territory of Delhi</span></div>",
          "NCW":"<div class='tooltip'>NCW<span class='tooltiptext'>National Commission of Women</span></div>",
          "NCWI":"<div class='tooltip'>NCWI<span class='tooltiptext'>The National Council of Women in India</span></div>",
          "NGO":"<div class='tooltip'>NGO<span class='tooltiptext'>Non-Governmental Organization</span></div>",
          "NPC":"<div class='tooltip'>NPC<span class='tooltiptext'>National Planning Commission</span></div>",
          "NRI":"<div class='tooltip'>NRI<span class='tooltiptext'>Non-Resident Indian</span></div>",
          "Ors.":"<div class='tooltip'>Ors.<span class='tooltiptext'>Others</span></div>",
          "M&E":"<div class='tooltip'>M&E<span class='tooltiptext'>Monitoring and Evaluation</span></div>",
          "M. A.":"<div class='tooltip'>M. A.<span class='tooltiptext'>Miscellaneous Application</span></div>",
          "M. Cr. C.":"<div class='tooltip'>M. Cr. C.<span class='tooltiptext'>Madras Criminal Cases</span></div>",
          "M.A.No.":"<div class='tooltip'>M.A.No.<span class='tooltiptext'>Miscellaneous Application Number</span></div>",
          "MF":"<div class='tooltip'>MF<span class='tooltiptext'>Medical Facilities</span></div>",
          "MLC":"<div class='tooltip'>MLC<span class='tooltiptext'>Report Medico Legal Case Report</span></div>",
          "MOHFW":"<div class='tooltip'>MOHFW<span class='tooltiptext'>The Ministry of Health and Family Welfare</span></div>",
          "MOU":"<div class='tooltip'>MOU<span class='tooltiptext'>Memorandum of Understanding</span></div>",
          "LCC":"<div class='tooltip'>LCC<span class='tooltiptext'>Local Complaint Committee</span></div>",
          "L.Q.R":"<div class='tooltip'>L.Q.R<span class='tooltiptext'>Law Quarterly Review</span></div>",
          "L.R.":"<div class='tooltip'>L.R.<span class='tooltiptext'>Legal Representative</span></div>",
          "LCWRI":"<div class='tooltip'>LCWRI<span class='tooltiptext'>Lawyers Collective Women's Rights Initiative</span></div>",
          "LSA":"<div class='tooltip'>LSA<span class='tooltiptext'>Legal Services Authority</span></div>",
          "JILI":"<div class='tooltip'>JILI<span class='tooltiptext'>Journal of Indian Law Institute</span></div>",
          "JMFC":"<div class='tooltip'>JMFC<span class='tooltiptext'>Judicial Magistrate First Class</span></div>",
          "KSSWB":"<div class='tooltip'>KSSWB<span class='tooltiptext'>Kerala State Social Welfare Board</span></div>",
          "AIDWA":"<div class='tooltip'>AIDWA<span class='tooltiptext'>All India Democratic Women's Association</span></div>",
          "AIWC":"<div class='tooltip'>AIWC<span class='tooltiptext'>All India Women's Conference</span></div>",
          "Anr.":"<div class='tooltip'>Anr.<span class='tooltiptext'>Another</span></div>",
          "AP":"<div class='tooltip'>AP<span class='tooltiptext'>Aggrieved Person</span></div>",
          "Art.":"<div class='tooltip'>Art.<span class='tooltiptext'>Article</span></div>",
          "ASJ":"<div class='tooltip'>ASJ<span class='tooltiptext'>Additional Sessions Judge</span></div>",
          "BHCR":"<div class='tooltip'>BHCR<span class='tooltiptext'>Bombay High Court Reporter</span></div>",
          "BLR":"<div class='tooltip'>BLR<span class='tooltiptext'>Bombay Law Reporter</span></div>",
          "Bom LR":"<div class='tooltip'>Bom LR<span class='tooltiptext'>Bombay Law Review</span></div>",
          "C.C No":"<div class='tooltip'>C.C No<span class='tooltiptext'>Civil Case Number</span></div>",
          "C.C. No.":"<div class='tooltip'>C.C. No.<span class='tooltiptext'>Criminal Case No.</span></div>",
          "C.P.C":"<div class='tooltip'>C.P.C<span class='tooltiptext'>Civil Procedure Code</span></div>",
          "CCS":"<div class='tooltip'>CCS<span class='tooltiptext'>Central Civil Services</span></div>",
          "CEDAW":"<div class='tooltip'>CEDAW<span class='tooltiptext'>Convention on the Elimination of all forms of Discrimination against women</span></div>",
          "CMP No":"<div class='tooltip'>CMP No<span class='tooltiptext'>Civil Miscellaneous Petition Number</span></div>",
          "CMRA":"<div class='tooltip'>CMRA<span class='tooltiptext'>Child Marriage Restraint Act</span></div>",
          "Co. Ltd.":"<div class='tooltip'>Co. Ltd.<span class='tooltiptext'>Company Limited</span></div>",
          "Cr WJC":"<div class='tooltip'>Cr WJC<span class='tooltiptext'>Criminal Writ Jurisdiction Case</span></div>",
          "Cr.P.C":"<div class='tooltip'>Cr.P.C<span class='tooltiptext'>Criminal Procedure Code</span></div>",
          "Crl Misc No.":"<div class='tooltip'>Crl Misc No.<span class='tooltiptext'>Criminal Miscellaneous Number</span></div>",
          "Crl. M. A":"<div class='tooltip'>Crl. M. A<span class='tooltiptext'>Criminal Miscellaneous Appeal</span></div>",
          "Crl. M. C.":"<div class='tooltip'>Crl. M. C.<span class='tooltiptext'>Criminal Miscellaneous Case</span></div>",
          "Crl. O. P.":"<div class='tooltip'>Crl. O. P.<span class='tooltiptext'>Criminal Original Petition</span></div>",
          "Crl. R.C No.":"<div class='tooltip'>Crl. R.C No.<span class='tooltiptext'>Criminal Revision Case Number</span></div>",
          "CSS":"<div class='tooltip'>CSS<span class='tooltiptext'>Centrally Sponsored Scheme</span></div>",
          "D.V":"<div class='tooltip'>D.V<span class='tooltiptext'>Domestic Violence</span></div>",
          "D/o":"<div class='tooltip'>D/o<span class='tooltiptext'>Daughter of</span></div>",
          "DIR":"<div class='tooltip'>DIR<span class='tooltiptext'>Domestic Incident Report</span></div>",
          "DVC No.":"<div class='tooltip'>DVC No.<span class='tooltiptext'>Domestic Violence Case Number</span></div>",
          "DWCD":"<div class='tooltip'>DWCD<span class='tooltiptext'>Department of Women and Child Development</span></div>",
          "e.g":"<div class='tooltip'>e.g<span class='tooltiptext'>Exempli Gratia (for example)</span></div>",
          "E.S.I.":"<div class='tooltip'>E.S.I.<span class='tooltiptext'>Employee's State Insurance</span></div>",
          "Edn.":"<div class='tooltip'>Edn.<span class='tooltiptext'>Edition</span></div>",
          "etc.":"<div class='tooltip'>etc.<span class='tooltiptext'>Etcetera (and so forth)</span></div>",
          "FB":"<div class='tooltip'>FB<span class='tooltiptext'>Full Bench</span></div>",
          "FCC":"<div class='tooltip'>FCC<span class='tooltiptext'>Family Counselling Centre</span></div>",
          "FIR":"<div class='tooltip'>FIR<span class='tooltiptext'>First Information Report</span></div>",
          "govt.":"<div class='tooltip'>govt.<span class='tooltiptext'>Government</span></div>",
          "GR":"<div class='tooltip'>GR<span class='tooltiptext'>Government Resolution</span></div>",
          "HAMA":"<div class='tooltip'>HAMA<span class='tooltiptext'>Hindu Adoption and Maintenance Act</span></div>",
          "Harv.L.R":"<div class='tooltip'>Harv.L.R<span class='tooltiptext'>Harvard Law Review</span></div>",
          "HAS":"<div class='tooltip'>HAS<span class='tooltiptext'>Hindu Succession Act</span></div>",
          "HC":"<div class='tooltip'>HC<span class='tooltiptext'>High Court</span></div>",
          "HUF":"<div class='tooltip'>HUF<span class='tooltiptext'>Hindu undivided family</span></div>",
          "I.A No":"<div class='tooltip'>I.A No<span class='tooltiptext'>Interlocutory Application Number</span></div>",
          "I.L.R":"<div class='tooltip'>I.L.R<span class='tooltiptext'>Indian Law Reporter</span></div>",
          "ICC":"<div class='tooltip'>ICC<span class='tooltiptext'>Internal Complaint Committee</span></div>",
          "ICCPR":"<div class='tooltip'>ICCPR<span class='tooltiptext'>International Covenant on Civil and Political Rights</span></div>",
          "ICESC":"<div class='tooltip'>ICESC<span class='tooltiptext'>International Covenant on Economic, Social and Cultural Rights</span></div>",
          "ICRW":"<div class='tooltip'>ICRW<span class='tooltiptext'>International Centre for Research on Women</span></div>",
          "ID":"<div class='tooltip'>ID<span class='tooltiptext'>Identity</span></div>",
          "IDA":"<div class='tooltip'>IDA<span class='tooltiptext'>Indian Divorce Act</span></div>",
          "IO":"<div class='tooltip'>IO<span class='tooltiptext'>Investigating Officer</span></div>",
          "IPC":"<div class='tooltip'>IPC<span class='tooltiptext'>Indian Penal Code, 1860</span></div>"

    };
    Object.keys(pairs).forEach(function (key) {
        str = str.split(key).join(pairs[key]);
    });
    return str;
}

